### ISSUE TITLE
What is the difference between process_eth_data.py process_eth_data_diverse.py?

### ISSUE THREAD

**Issue by SeongjuLee** [MediaBrain-SJTU/EqMotion#2]
Could you explain the difference?

**Comment by sjtuxcx** [comment]
Here we only use process_eth_data_diverse.py. You can ignore process_eth_data.py. Thanks!

**Comment by SeongjuLee** [comment]
Thanks for your replying, then can you explain the reason why the maximum number of neighbors is set with 2/3/1 for univ/zara1/else for ETH-UCY dataset?

**Comment by sjtuxcx** [comment]
Sorry for the late reply! I didn't check out the issues these days. We determine the maximum number of neighbors by some simple observations that in univ/zara1 there are more interacted agents in the scenes and in other subsets the agent tends to walk individually.
