### ISSUE TITLE
Results on Human3.6M

### ISSUE THREAD

**Issue by wangzhihao-coder** [MediaBrain-SJTU/EqMotion#3]
Thank you so much for your excellent work. I have run the short-term training code on Human3.6M in the repository, but I was unable to reproduce the results in the paper.

My results are as follows
![1](https://github.com/MediaBrain-SJTU/EqMotion/assets/53221219/9975b7fd-8844-41c6-9cc4-586d28ec7ba7)

I notice that the biggest improvement in the results of the paper come from the "discussion" and "posing", but my reproduced results don't significantly improve in these two categories.

![2](https://github.com/MediaBrain-SJTU/EqMotion/assets/53221219/94bdeed6-4548-469b-826a-4f0dbde6e10c)

I guess the code in the repository is missing some training configuration or data augmentation methods.

**Comment by sjtuxcx** [comment]
Hi, it is confusing since I have rerun the code and the result can be reproduced. The most likely reason may come from the environment configuration. Can you provide your environment information as well as the Pytorch version?

**Comment by sjtuxcx** [comment]
Moreover, can you also check if your dataset is correct? The dataset we used comes from https://github.com/limaosen0/DMGNN/tree/master/data/h3.6m.

**Comment by wangzhihao-coder** [comment]
I'm able to get the results of the paper using the repository's checkpoint. And I have checked my training dataset against DMGNN's dataset and found no differences.

My local environment is: `python == 3.8.5  pytorch == 1.9.0  cuda == 11.2`

**Comment by sjtuxcx** [comment]
From the feedback from other researchers and my reproduction, the current code can reproduce the paper result. Would you please 1. Run the code multiple times 2. Use the pytorch version 1.8.0 (the version I am using) to have another try?
